export default {
    ADD_PRODUCT: 'add_product',
    ADD_REVIEW: 'add_review',
    ADD_SELECTED_FLAVOR: 'add_selected_flavor',
    AUTH_ERROR: 'auth_error',
    BROWSE_ALL_JUICES: 'browse_all_juice',
    CLEAR_AUTH_ERROR: 'clear-auth-error',
    CLEAR_REVIEW_FLAVORS: 'clear_review_flavors',
    CREATE_ACCOUNT: 'create_account',
    GET_CATEGORIES: 'get_categories',
    GET_CHART_DATA: 'get_chart_data',
    GET_LIST_DATA: 'get_list_data',
    GET_RANDOM_JUICE: 'get_random_juice',
    GET_SINGLE_ITEM_REVIEWS: 'get_single_item_reviews',
    PULL_JUICE_DATA: 'pull_juice_data',
    SEARCH_BY_ANY: 'search_by_any',
    SEARCH_BY_NAME: 'search_by_name',
    SET_CATEGORY: 'set_category',
    SET_FLAVOR: 'set_flavor',
    SET_SEARCH_TERM: 'set-search-term',
    SIGN_IN: 'sign_in',
    SIGN_OUT: 'sign_out',
    SIGN_UP: 'sign_up',
    SINGLE_ITEM: 'single_item',
};
