export default {

    GET_LIST_DATA: "get_list_data",
    ADD_PRODUCT: "add_product",
    CREATE_ACCOUNT: "create_account",
    ADD_REVIEW: "add_review",
    PULL_JUICE_DATA: "pull_juice_data",
    SEARCH_BY_NAME: "search_by_name",
    SEARCH_BY_ANY: "search_by_any",
    BROWSE_ALL_JUICES: "browse_all_juice",
    GET_RANDOM_JUICE: "get_random_juice",
    SINGLE_ITEM: "single_item",
    GET_CATEGORIES: "get_categories",
    SET_CATEGORY: "set_category",
    SET_FLAVOR: "set_flavor",
    ADD_SELECTED_FLAVOR: "add_selected_flavor",
    GET_SINGLE_ITEM_REVIEWS: "get_single_item_reviews",
    GET_SINGLE_ITEM_REVIEWS: "get_single_item_reviews",
    SIGN_UP: 'sign_up',
    SIGN_IN: 'sign_in',
    SIGN_OUT: 'sign_out',
    AUTH_ERROR: 'auth_error',
    CLEAR_AUTH_ERROR: 'clear-auth-error',
    SET_SEARCH_TERM: "set-search-term",
    GET_CHART_DATA: "get_chart_data"
};
